FROM neo4j:5

# Install Python and necessary libraries
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies for Neo4j
RUN pip3 install py2neo pandas

# Set working directory for Python scripts
WORKDIR /app

# Copy Python scripts into the container
COPY run_metrics.py metrics.sc neo4j_export.py /app/
RUN chmod +x /app/run_metrics.py


